### ISSUE TITLE
Remove chart paddings

### ISSUE THREAD

**Issue by javichaques** [patrykandpatrick/vico#238]
Hi, I want to add a chart without a legend but I don't know how to remove the side padding or the bottom one. Is it possible to do this? 
I'm using version 1.6.5 with compose. Thanks!

**Current** 
![current](https://user-images.githubusercontent.com/6851391/232087331-30b3c3d2-d9db-4ac1-ad1c-591c8b473e4a.png)

**Expect**
![expect](https://user-images.githubusercontent.com/6851391/232087339-af12dcc6-e6b5-4230-89a9-af71b69d7332.png)

**Comment by patrickmichalik** [comment]
Hello! Please see [this comment](https://github.com/patrykandpatrick/vico/issues/229#issuecomment-1500189774) for information on how to remove the gaps on the sides of the chart. We’re currently working on a change that will make it easier to remove this empty space. The gap at the bottom of the chart seems to be a bug. The issue will be resolved with the next update.

**Comment by patrickmichalik** [comment]
I wanted to share a quick update on the bottom gap. To remove it, you can set the line width to zero. This shouldn’t produce any unwanted side effects, since the line already has the same color as the fill (or perhaps it’s transparent). As it turns out, the gap isn’t a bug—consider the situation presented below. I apologize for the confusion.

![](https://user-images.githubusercontent.com/120058021/232107999-2a640a4e-01a6-4e8c-b25c-5db658b28010.png)

**Comment by javichaques** [comment]
Hi, thanks for the quick response. I was able to solve it with your comments, thanks

**Comment by patrickmichalik** [comment]
You’re welcome!
