### ISSUE TITLE
How to determine custom step in line chart for y-axis values?

### ISSUE THREAD

**Issue by varchar20** [patrykandpatrick/vico#243]
Hi,

I'd like to specify a custom step between the values on the y-axis, but I don't see any option for that.

As far as I can see, the function to calculate that step is inside `VerticalAxis` class:
```
    private fun MeasureContext.getLabels(
        maxLabelCount: Int = this@VerticalAxis.maxLabelCount,
    ): List<CharSequence> {
        val chartValues = chartValuesManager.getChartValues(position)
        val cacheKey = LABELS_KEY + position + maxLabelCount
        return getOrPutExtra(key = cacheKey) {
            labels.clear()
            val step = (chartValues.maxY - chartValues.minY) / maxLabelCount
            for (index in 0..maxLabelCount) {
                val value = chartValues.minY + step * index
                labels += valueFormatter.formatValue(value, chartValues)
            }
            labels
        }
    }
```
So the step is calculated as the difference of `maxY` and `minY` divided by `maxLabelCount`, but I'd like this step not to be "chipped" between the given entries that are provided for `ChartEntryModelProducer`.

**For example:**
I have such a data sets: [0, 9, 27, 35] and [0, 9, 18, 27] from which I'm creating `List<List<CustomChartEntry>>` that is provided for `ChartEntryModelProducer`. I'd like the chart to display only these values on the y-axis and the guideline should also be drawn only for these values.

Is it possible?

**Comment by varchar20** [comment]
Thank you for your answer!

A custom `VerticalAxis` implementation, so should I copy the entire class, but change this block of code where is the calculation of the y-axis step?

**Comment by patrickmichalik** [comment]
Hello! From what I can tell, what you’d like to do is not change the step but have labels added at irregular intervals. The step can already be changed, albeit indirectly. However, as you’ve mentioned, you’d like to see the following values along the axis: 0, 9, 18, 27, and 35. Here, we have four steps of nine and, between 27 and 35, one step of eight. If the last value were 36, you’d be able to achieve the desired result by reducing the maximum label count, but because it is 35, a custom `Axis` implementation is needed. Changing the value of the `step` variable won’t suffice. `VerticalAxis` draws labels at regular intervals, and you’ll need to change that.

**Comment by patrickmichalik** [comment]
I’m afraid this isn’t possible at the moment, @dianastraliciuc. The maximum and minimum values’ labels are always displayed. Let’s generalize everything requested here as greater control over what labels `VerticalAxis` shows, and let’s use this issue to track the feature request.

**Comment by patrickmichalik** [comment]
[Vico 1.9.0](https://github.com/patrykandpatrick/vico/releases/tag/v1.9.0) introduces `AxisItemPlacer.Vertical`, which lets you fully customize for what _y_ values a `VerticalAxis` displays labels, ticks, and guidelines. Cheers!
