### ISSUE TITLE
Is it possible to show X and Y values on drag Marker on other components(a separate Text for example)?

### ISSUE THREAD

**Issue by abderhim** [patrykandpatrick/vico#249]

**Comment by abderhim** [comment]
I noticed only Y value is showed, i want X value after formatting maybe and i want to show them in a separate component.

**Comment by patrickmichalik** [comment]
Hello! `MarkerLabelFormatter#getLabel` gives you access to a list of `Marker.EntryModel` instances, so both the _x_ values and the _y_ values of the marked entries can be accessed and displayed. `Marker#draw` enables you to draw any number of components. However, because `MarkerLabelFormatter#getLabel` returns a single string, in order to display different bits of entry data in different components, you’d have to join this data into one string in `MarkerLabelFormatter#getLabel` and split the string in `Marker#draw`.

**Comment by galihif** [comment]
Hi, could you provide some examples of how to label the x values on your wiki? Thanks
