### ISSUE TITLE
Offset y-axis with multiple charts

### ISSUE THREAD

**Issue by moorekevin** [patrykandpatrick/vico#253]
**Description**
We have a chart that is composed of up to 4 linecharts in one. We would like each linechart to be offset on the y-axis with a number so the linecharts are not stacked. Is this in any way possible with Vico without manually adding the offset to all the y-values?

I hope this is the right place to ask. Thanks in advance, and thanks for this awesome library!

**Comment by patrickmichalik** [comment]
Hello! Thank you for the kind words. `ComposedChart` allows for the independent scaling of charts, but you can’t have more than two vertically independent coordinate systems, since no more than two vertical axes can be displayed. In your case, the _y_ values should be adjusted—as such, in the Cartesian coordinate system, if two lines don’t intersect at a given _x_ coordinate, it must be the case that the lines have different _y_ values for the _x_ coordinate in question.

**Comment by moorekevin** [comment]
Thank you for your clarification. Is it possible to synchronize the scrolling if we instead made 4 separate graphs? So 4 boxes with their own coordinate system.

**Comment by patrickmichalik** [comment]
Because scroll listeners can be added, and programmatic scrolling is supported, this should be possible, but I suspect a significant amount of work would be required to make such a solution work reliably. Generally, we don’t recommend placing multiple instances of either of the two top-level components on top of one another in lieu of using `ComposedChart` or a `LineChart` with multiple lines.

**Comment by moorekevin** [comment]
Okay, I see, thank you. Last question, is it possible to somehow manually change the marker values shown using your MarkerComponent? In our instance we will offset the graphs in the ComposedChart by manually adding an offset to the y values of each graph. Then we would like the marker to not actually show the offset value, therefore we would like to subtract the offset from the values displayed from the marker.

**Comment by moorekevin** [comment]
I figured it out by making my own custom MarkerComponent and just changing the text value from the labelFormatter.getLabel using string formatting. However now the problem is that the text color for the marker label is all black instead of corresponding to the chart colors. Where would I go and manually change the text coloring for the marker label?

**Comment by patrickmichalik** [comment]
You can use `Spannable`—I’d suggest taking a look at [the `DefaultMarkerLabelFormatter` definition](https://github.com/patrykandpatrick/vico/blob/ba643c66417d7a7365f1ae0fed91e779b6729b54/vico/core/src/main/java/com/patrykandpatrick/vico/core/marker/DefaultMarkerLabelFormatter.kt).
