### ISSUE TITLE
No maxLabelCount for bottomAxis?

### ISSUE THREAD

**Issue by NzoSifou** [patrykandpatrick/vico#267]
Hello!

I use "maxLabelCount" for my startAxis to see only eight values in the vertical axis, but I want to do the same with my horizontal axis but I can't figure out how to do it, because there isn't a "maxLabelCount" method and I don't see how else I could do that for my horizontal axis.
Can someone help me for this, it will be very nice!
(PS : Sorry for my approximately English, I'm French)

Bye!

**Comment by patrickmichalik** [comment]
Hello! For `HorizontalAxis`, the equivalent of `maxLabelCount` would be `HorizontalAxis.TickPosition.Center#spacing`, as mentioned [here](https://patrykandpatrick.com/vico/wiki/axes). Rather than specifying the label count, you can define how often labels are to be drawn. I should also mention that we’re currently working on a new API that will improve how matters such as label spacing are handled.

**Comment by NzoSifou** [comment]
Hi!

Sorry for the late reply,

I did not realize that this parameter allows to do that, the problem is that it's not that I want exactly...
I have numbers on the horizontal axis from 70 to 500 (70, 95, 160, 250, 350, 450 and 500) and I want to show only these numbers (with the 0 at the start) on my horizontal axis.

The problem with the tickPosition is that (here a screenshot):
![image](https://github.com/patrykandpatrick/vico/assets/54418244/de29fc21-ec27-456d-a443-78a0fab86a7c)
And here I have a spacing of 5 and I can't do something better :/

Thanks for your time and your help I appreciate it!

**Comment by patrickmichalik** [comment]
Got it. I’m afraid this isn’t supported at the moment, but we’ll be adding such functionality.

**Comment by patrickmichalik** [comment]
Because this feature has already been requested in issue #190, I’ll be closing this one. Updates will be shared under issue #190.
