### ISSUE TITLE
Markers do not show on first click

### ISSUE THREAD

**Issue by joharei** [patrykandpatrick/vico#358]
**Describe the bug**
Markers do not show the first time the graph is clicked. From the second time onwards they do show. `MarkerVisibilityChangeListener.onMarkerShown` is also not being called the first time.

**Module**

- [x] `compose`
- [ ] `views`
- [ ] `compose-m2`
- [ ] `compose-m3`
- [ ] `core` (select if none of the above apply)

**To reproduce**
1. Add a marker
2. Press the graph. Nothing happens.
3. Press the graph again. The marker shows.

**Expected behavior**
The marker should show also the first time the graph is pressed.

**Android versions**
Tested on APIs 21 and 34.

**Comment by patrickmichalik** [comment]
Hello! Thanks for the report. Does this also happen in the sample app (which you can get [here](https://github.com/patrykandpatrick/vico/releases/tag/v1.9.2))? I can’t seem to reproduce the issue there. If it doesn’t, could you provide a minimal reproducible example?

**Comment by joharei** [comment]
It does not happen in the sample app. I'll investigate tomorrow.

**Comment by patrickmichalik** [comment]
Thanks!

**Comment by joharei** [comment]
Hi, I managed to create a minimal repro here: https://github.com/joharei/VicoFirstClickRepro

**Comment by patrickmichalik** [comment]
Perfect. Cheers!

**Comment by patrickmichalik** [comment]
We’ve looked into the matter, and it looks like the problem is caused by version 2023.08.00 of the Jetpack Compose BOM. Vico 1.9.2 uses version 2023.06.01, and downgrading the BOM in your project seems to resolve the issue. There’s been some kind of breaking change in Jetpack Compose, I suspect. For the next version of Vico, we’ll update the BOM and make whatever changes version 2023.08.00 requires, which should resolve the problem you’re facing. I’ll let you know when the update is available.

**Comment by patrickmichalik** [comment]
[Vico 1.10.0](https://github.com/patrykandpatrick/vico/releases/tag/v1.10.0), which fixes this, is now available. Cheers!
