### ISSUE TITLE
Jumping animation when setting minY and maxY values in AxisValuesOverrider independently of ChartEntryModel

### ISSUE THREAD

**Issue by Leedwon** [patrykandpatrick/vico#363]
**Describe the bug**
There is a weird animation behaviour when switching from positive entries to negative ones with `AxisValuesOverrider`.

`AxisValueOverrider` is set up in such a way that it set's `minY` to `min(0f, allEntries.minOf { it.y })` and `maxY` to `max(0f, allEntries.maxOf { it.y })`. When entries change from list with positive y values to list with negative y values (also containing less elements) animation has a weird behaviour (see video from MRE).

We also tried using `diffAnimationSpec = snap()` it helps in MRE, but in our prod app the behaviour is still buggy (see Video with snap animation)

**Module**

- [x] `compose`
- [ ] `views`
- [ ] `compose-m2`
- [ ] `compose-m3`
- [ ] `core` (select if none of the above apply)

**To reproduce**
[MRE repo](https://github.com/Leedwon/VicoAnimationMRE)

**Expected behavior**
Good enough solution would be: when changing from one data set containing more entries to another with snap animation there should be no additional data points drawn with y=0 (see Video with snap animation for context)

**Screenshots**

Video from MRE showcasing animation issue:

[vico-anim-bug.webm](https://github.com/patrykandpatrick/vico/assets/29312085/0e185fb6-df26-4927-8602-2aef5b20922d)

Video with snap animation:

https://github.com/patrykandpatrick/vico/assets/29312085/54e22192-229b-4112-a1b7-13bba1f5f8cc

**Comment by patrickmichalik** [comment]
Hello! Thanks for the report. We advise against changing a chart’s `AxisValuesOverrider` in this manner. The current `ChartEntryModel` is passed to `getMinX`, `getMaxX`, `getMaxY`, and `getMinY`, and one should override the axis values based on this `ChartEntryModel`’s properties. Because Vico’s difference animations work by altering the `ChartEntryModel`, it’s important that, as `ChartEntryModel#minY` and `ChartEntryModel#maxY` gradually change, there are no jumps in the values returned by the chart’s `AxisValuesOverrider`. We understand that this isn’t optimal—in most cases, it’d be preferable if the `AxisValuesOverrider` were immediately given the target `ChartEntryModel`, the axis values changed, and the chart were subsequently animated. This appears to be what you were looking to achieve. I’m afraid that, at the moment, this isn’t possible, but we’re currently reworking how difference animations are implemented, and once these changes are available, this behavior will be the default. I’ll keep you updated.

Regarding disabling difference animations, in [Vico 1.11.0](https://github.com/patrykandpatrick/vico/releases/tag/v1.11.0), the `diffAnimationSpec` parameter of the `Chart` composable function is nullable. Passing `null` disables difference animations. Could you take a look if that helps? Because the `snap` solution works properly in the MRE project, we are, unfortunately, unable to determine why it’s not working as expected in your app. We’d need an example where the issue is present.

**Comment by Leedwon** [comment]
Hi, many thanks for the quick response! I tried using 1.11.0 and passing null as `diffAnimationSpec`, but unfortunately the result is the same as with snap animation.

Regarding your advice on the usage of AxisValuesOverrider:
> We advise against changing a chart’s AxisValuesOverrider in this manner. The current ChartEntryModel is passed to getMinX, getMaxX, getMaxY, and getMinY, and one should override the axis values based on this ChartEntryModel’s properties.

Here's more context for our use case:
Our data is segmented into chunks, each chunk contains five entries and each entry contains a date. We display one such chunk at a time on the graph. So, for example, our x-axis might present dates like `[22.08, 23.08, 24.08, 25.08, 26.08]` with their corresponding y values. We use `AxisValuesOverrider` to ensure `minY` matches the minimum y-value across the dataset, and similarly for `maxY`. Without this, as users navigate between chunks, they could see shifts in the y-axis scale. For instance, one chunk might have a `minY = 0` and `maxY = 10`, while the next displays a range from `minY = -20` to `maxY = 100`. Could we achieve it without using `AxisValuesOverrider` or does our usage align with its intended purpose?

**Comment by patrickmichalik** [comment]
Thanks for the context! What you’ve described does align with the intended purpose of `AxisValuesOverrider`. However, I don’t entirely understand how this relates to the examples provided. You’ve mentioned that the _y_ range remains unchanged, which prevents shifts, but in both recordings, when the data changes, so does the _y_ range. For example, in the recording from your app, taking a look at the vertical axis on the left, we can see that the range is initially 0 to 2, and then it changes to −197 to 0. This change is where the animation problem stems from. (Just to reiterate, the changes that we’re working on right now will make things less restrictive, and it’ll be possible to have such an instantaneous _y_ range change followed by a smooth chart animation.) Is this change in _y_ range part of the issue? That is, is the aim for it not to occur?

Regarding disabling difference animations, I’m sorry to hear that the `null` solution didn’t help. It sounds like there might be an error in how you update the chart data. It’s not impossible that this is a bug, of course, but I’d consider that the less likely option, especially seeing that the issue doesn’t occur in the MRE app. Do you think you’d be able to create and share an example where the problem can be observed?

**Comment by patrickmichalik** [comment]
To give you a better understanding of what I’m talking about, I’ve modified the `MainActivity.kt` file from the MRE project such that `AxisValuesOverrider` is used in accordance with our recommendations. Below is what `git diff` returns. GitHub should format this output nicely. Once we’ve reworked how difference animations are implemented—which is our current priority—such a setup should give you smooth transitions. For now, it doesn’t help much as far as animations are concerned, but it is generally a bit more robust, and it works as expected when you turn off difference animations, which I’ve done here. If your app includes a setup similar to what is found in the MRE project, I’d suggest updating it analogously. This might have something to do with the issue where the chart doesn’t behave as expected with difference animations disabled.

```diff
diff --git a/app/src/main/java/com/example/vicoanimation/MainActivity.kt b/app/src/main/java/com/example/vicoanimation/MainActivity.kt
index ea01d74..5d7bef9 100644
--- a/app/src/main/java/com/example/vicoanimation/MainActivity.kt
+++ b/app/src/main/java/com/example/vicoanimation/MainActivity.kt
@@ -3,6 +3,7 @@ package com.example.vicoanimation
 import android.os.Bundle
 import androidx.activity.ComponentActivity
 import androidx.activity.compose.setContent
+import androidx.compose.animation.core.snap
 import androidx.compose.foundation.layout.Column
 import androidx.compose.foundation.layout.fillMaxSize
 import androidx.compose.foundation.layout.padding
@@ -13,7 +14,6 @@ import androidx.compose.material3.Text
 import androidx.compose.runtime.Composable
 import androidx.compose.runtime.LaunchedEffect
 import androidx.compose.runtime.getValue
-import androidx.compose.runtime.mutableFloatStateOf
 import androidx.compose.runtime.mutableIntStateOf
 import androidx.compose.runtime.remember
 import androidx.compose.runtime.setValue
@@ -27,6 +27,7 @@ import com.patrykandpatrick.vico.compose.chart.line.lineChart
 import com.patrykandpatrick.vico.compose.style.ProvideChartStyle
 import com.patrykandpatrick.vico.core.chart.values.AxisValuesOverrider
 import com.patrykandpatrick.vico.core.entry.ChartEntry
+import com.patrykandpatrick.vico.core.entry.ChartEntryModel
 import com.patrykandpatrick.vico.core.entry.ChartEntryModelProducer
 import kotlin.math.max
 import kotlin.math.min
@@ -52,12 +53,8 @@ private fun VicoMre() {
     val chartEntryModelProducer = remember { ChartEntryModelProducer() }
 
     var clicks by remember { mutableIntStateOf(0) }
-    var minY by remember { mutableFloatStateOf(0f) }
-    var maxY by remember { mutableFloatStateOf(0f) }
 
     fun setData(data: List<List<SimpleChartEntry>>) {
-        minY = min(0f, data.flatten().minOf { it.y })
-        maxY = max(data.flatten().maxOf { it.y }, 0f)
         chartEntryModelProducer.setEntries(data)
     }
 
@@ -66,11 +63,7 @@ private fun VicoMre() {
     }
 
     Column(modifier = Modifier.padding(16.dp)) {
-        Chart(
-            minY = minY,
-            maxY = maxY,
-            chartEntryModelProducer = chartEntryModelProducer
-        )
+        Chart(chartEntryModelProducer)
         Button(
             onClick = {
                 clicks++
@@ -83,13 +76,15 @@ private fun VicoMre() {
 }
 
 @Composable
-private fun Chart(
-    minY: Float,
-    maxY: Float,
-    chartEntryModelProducer: ChartEntryModelProducer
-) {
-    val axisValuesOverrider = remember(minY, maxY) {
-        AxisValuesOverrider.fixed(minY = minY, maxY = maxY)
+private fun Chart(chartEntryModelProducer: ChartEntryModelProducer) {
+    val axisValuesOverrider = remember {
+        object : AxisValuesOverrider<ChartEntryModel> {
+            override fun getMinY(model: ChartEntryModel) =
+                model.entries.flatten().minOfOrNull { it.y }?.coerceAtMost(0f) ?: 0f
+
+            override fun getMaxY(model: ChartEntryModel) =
+                model.entries.flatten().maxOfOrNull { it.y }?.coerceAtLeast(0f) ?: 0f
+        }
     }
 
     ProvideChartStyle(rememberChartStyle()) {
@@ -98,6 +93,7 @@ private fun Chart(
             chartModelProducer = chartEntryModelProducer,
             startAxis = rememberStartAxis(),
             bottomAxis = rememberBottomAxis(guideline = null),
+            diffAnimationSpec = snap(),
             runInitialAnimation = false
         )
     }
```

**Comment by Leedwon** [comment]
Thanks for the quick answer! You are right, the use case I described doesn't relate to the provided example. I presented only part of our use case as I wanted keep the example relatively simple and validate my understanding of `AxisValueOverrider`. Now I can see that without having more context it could be a bit confusing, sorry about that. I'll try to provide more info about the use case below.

The entire use case looks like follow:
- There are multiple data sets available for users.
- Each data set contains multiple chunks.
- Each chunk contains 5 entries. Each entry contain `date` that is mapped to x-axis and `value` that is mapped to y-axis
- Users can switch between data sets
- Within the data set users can switch between chunks
- Graph displays one chunk at a time
- `MinY` and `MaxY` are calculated based on min and max values from one data set, so when data set changes new values must be calculated (that's what you can see in the snap-issue.mov example)
- Only data from current chunk is displayed on the chart, so when chunk changes new entries are passed to `ChartEntryModelProducer`

Simplified version of the actual data structure could look like this:
```Kotlin
data class Entry(
    val date: LocalDate,
    val value: Float,
)

data class Chunk(
    val entries: List<Entry>
)

data class DataSet(
    val chunks: List<Chunk>
)

val exampleChunks = listOf(
    Chunk(
        entries = listOf(
            Entry(date = LocalDate.of(2023, 8, 20), value = 1.0f),
            Entry(date = LocalDate.of(2023, 8, 21), value = 2.0f),
            Entry(date = LocalDate.of(2023, 8, 22), value = 3.0f),
            Entry(date = LocalDate.of(2023, 8, 23), value = 4.0f),
            Entry(date = LocalDate.of(2023, 8, 24), value = 5.0f),
        )
    ),
    Chunk(
        entries = listOf(
            Entry(date = LocalDate.of(2023, 8, 25), value = 10.0f),
            Entry(date = LocalDate.of(2023, 8, 26), value = 11.0f),
            Entry(date = LocalDate.of(2023, 8, 27), value = 12.0f),
            Entry(date = LocalDate.of(2023, 8, 28), value = 13.0f),
            Entry(date = LocalDate.of(2023, 8, 29), value = 14.0f),
        )
    ),
)

val dataSets = listOf(
    DataSet(exampleChunks),
    DataSet(anotherExampleChunks),
    // ... and so on
)
```

I'm also attaching the diagram that I hope will provide more context:
![ChartFlow](https://github.com/patrykandpatrick/vico/assets/29312085/27132414-ada5-4f44-b275-973c765a5924)

I think that now I understand what you mean by using `ChartEntryModel` with `AxisValuesOverrider`, many thanks for the detailed description! Please correct me if I'm wrong, but for the use case I described using `AxisValuesOverrider` with `model: ChartEntryModel` won't work as intended, because `model` contains only data from current chunk, while we want to calculate `minY` and `maxY` based on data from current data set.

**Comment by Leedwon** [comment]
If you don't mind I updated title of this issue. I think this one describes better the actual issue

**Comment by patrickmichalik** [comment]
Thanks for the detailed description of the use case! Everything’s clear now. You’re right—simply using `model.minY` and `model.maxY` in the `AxisValuesOverrider` functions would be insufficient. Because the use case is more complex than I initially thought, let me elaborate on what I’ve explained above. As such, the issue here isn’t which `ChartEntryModel`’s properties are read, but rather whether changes that should occur at the same time are, in fact, synchronized. Animations aside, when you update a chart’s data via `ChartEntryModelProducer#setEntries` and then recompose it with a new `AxisValuesOverrider`, you have no guarantee that these two updates will occur at the same time. `ChartEntryModelProducer#setEntries` runs some calculations on a separate thread and updates the chart once it’s completed those calculations. The chart may receive the new data before or after it receives the new `AxisValuesOverrider`, which can cause issues. (I believe this is what’s happening in your app.) Only in the `AxisValuesOverrider` functions can you reliably determine what data your chart is displaying at a given time.

I believe it’d be possible to achieve the result you’re looking for without introducing this problematic `AxisValuesOverrider`-replacing mechanism. The key point is that, by using `model.id` in the `AxisValuesOverrider` functions, you can detect data updates. However, since a smooth transition will be achievable here only once we’ve reworked how difference animations are implemented, I have a different suggestion. You could, for the time being, avoid using `ChartEntryModelProducer` entirely, instead utilizing the overload of the `Chart` composable function that accepts a `ChartEntryModel`. All animation-related logic will be bypassed, and you’ll be able to keep the `AxisValuesOverrider`-replacing mechanism, perhaps with some small changes. This will, in effect, give you the result described under “Expected behavior.” It’ll require less work than figuring out how to stick to `ChartEntryModelProducer` and avoid changing the chart’s `AxisValuesOverrider` implementation more than once, which would have no benefit for now, since you’d have to turn off difference animations anyways. I’d suggest looking into that once we’ve reworked difference animations and released an update.

I’ve created a quick example, and I enclose a screen recording. The _y_ range changes as you’ve described, and the issue where some points don’t disappear soon enough doesn’t occur. Please let me know your thoughts. I’ll be happy to clean up the code and share it with you. Regarding the title change, it looks good. Please feel free to edit the issue title to your liking—we don’t mind.

https://github.com/patrykandpatrick/vico/assets/120058021/1fca7d61-c0b7-4bba-aaf9-44e614e83819

**Comment by Leedwon** [comment]
Hi, sorry for late response. I tried to implement the solution that you proposed and it is working just fine and is good enough for our use case, many thanks for your help! I will close this issue then 🙂.

**Comment by patrickmichalik** [comment]
Hello! [Vico 1.13.0](https://github.com/patrykandpatrick/vico/releases/tag/v1.13.0) includes two changes that are relevant here. First, it introduces a new animation system, which resolves the issue of both the _y_ range and the _y_ values being animated. When there’s a data update, the `AxisValuesOverrider` functions are called once, the _y_ range is updated, and the chart is smoothly animated. Second, extras have been added to `ChartEntryModelProducer` and `ComposedChartEntryModelProducer`. Extras are to be used for auxiliary information that should be in sync with the data. In your chart, you could use an extra to store the currently selected data set’s _y_ range. Your `AxisValuesOverrider` would then read this extra.

With these two changes, you’d be able to switch back to `ChartEntryModelProducer` and use difference animations. No shifts or flashes should occur. The solution proposed [here](https://github.com/patrykandpatrick/vico/issues/363#issuecomment-1691419001) remains perfectly valid, of course. If you have any questions, feel free to let me know. Thanks again!

**Comment by patrickmichalik** [comment]
Sounds good. You’re welcome!
