### ISSUE TITLE
At the beginning and at the end the label of bottom axis is cut off if you add a point to the lineChart

### ISSUE THREAD

**Issue by TimoninD** [patrykandpatrick/vico#447]
### How to reproduce

[unworking_charts.patch](https://github.com/patrykandpatrick/vico/files/13064421/unworking_charts.patch)
You can try it patch in Vico repository and run sample. The third graph will be cropped

<img width="286" alt="image" src="https://github.com/patrykandpatrick/vico/assets/31082648/b184dfe7-0e54-404f-9048-87eb640c5673">

### Observed behavior

I would like to be able to draw a static graph with any number of uncut labels on the screen. Or be able to set this amount yourself. Because now it is impossible to display even all days of the week by bottom axis

### Expected behavior

At the beginning and at the end the label of bottom axis is cut off if you add a point to the lineChart

### Vico version(s)

Latest stable version

### Android version(s)

34

**Comment by patrickmichalik** [comment]
Hello! Thanks for the report. The first label is truncated because there isn’t enough room for it. More horizontal padding is required. You can use the parameters of `HorizontalLayout.FullWidth.default` to add such padding. [Vico 1.13.0 Alpha 7](https://github.com/patrykandpatrick/vico/releases/tag/v1.13.0-alpha.7) introduced the ability to add unscalable padding, which would be preferable here. Vico 1.13.0 Alpha 9, which we plan on releasing within a couple of hours, will introduce an option that automatically adds the required amount of padding, ensuring that extreme `HorizontalAxis` labels are visible. Because the behavior described isn’t a bug, and the aforementioned new feature has already been requested, I’ll be closing this issue. I’ll let you know when Vico 1.13.0 Alpha 9 is available.

**Comment by patrickmichalik** [comment]
[Vico 1.13.0 Alpha 9](https://github.com/patrykandpatrick/vico/releases/tag/v1.13.0-alpha.9) is now rolling out. `AxisItemPlacer.Horizontal.default(addExtremeLabelPadding = true)` instructs a `HorizontalAxis` to make room for its extreme labels.

<img src="https://github.com/patrykandpatrick/vico/assets/120058021/5ec0df58-7d59-4d0d-b8c1-b1b04d059194" width="360" />
