### ISSUE TITLE
X Axis is wrapping

### ISSUE THREAD

**Issue by spmatthews03** [patrykandpatrick/vico#452]
### How to reproduce

I saw this as an issue before, but I have ampm hours as my bottom axis, if I have 11pm 12am 1am, I get a graph that has index 0 and 1, then index 23... and 22 null values in between. I understand things should be in order, but it should logically know that 12am the next day is still in sequence

### Observed behavior

NA

### Expected behavior

Not to wrap

### Vico version(s)

Latest stable version

### Android version(s)

All

**Comment by patrickmichalik** [comment]
Hello! Vico’s charts are based on Cartesian planes, and no assumptions are made based on the data. The library isn’t aware that your _x_ values represent hours. The chart is drawn in a manner that’s mathematically consistent with the provided coordinates. To have the three entries drawn at equal intervals, please update their _x_ values accordingly—you could use Unix timestamps or consecutive integers, for example. As mentioned [in the API reference](https://patrykandpatrick.com/vico/api/core/com.patrykandpatrick.vico.core.entry/-chart-entry/x), `ChartEntry#x` is the `ChartEntry`’s _x_ coordinate, not a label. Label customization is carried out via `AxisLabelFormatter`. Because this isn’t a bug, I’ll be closing the issue, but if you have any further questions, please feel free to comment.
