### ISSUE TITLE
Dataset for a single point on the x-axis causes "java.lang.IllegalArgumentException: The precision of the x values is too large. The maximum is two decimal places."

### ISSUE THREAD

**Issue by anvuks** [patrykandpatrick/vico#455]
### How to reproduce

Create a chart and set the following dataset:
```kotlin
val xValue = 123 // not losing precision when converted to float
chartView.setModel(ChartEntryModelProducer(listOf(entryOf(xValue, 5), entryOf(xValue, 20))).getModel())
```

The dataset causes this exception to be thrown:
```kotlin
Caused by: java.lang.IllegalArgumentException: The precision of the x values is too large. The maximum is two decimal places.
  at com.patrykandpatrick.vico.core.entry.ChartEntryExtensionsKt.calculateXGcd(ChartEntryExtensions.kt:94)
  at com.patrykandpatrick.vico.core.entry.ChartEntryModelProducer.getInternalModel(ChartEntryModelProducer.kt:137)
  at com.patrykandpatrick.vico.core.entry.ChartEntryModelProducer.getInternalModel$default(ChartEntryModelProducer.kt:120)
  at com.patrykandpatrick.vico.core.entry.ChartEntryModelProducer.getModel(ChartEntryModelProducer.kt:144)
  at com.myapplication.MainActivity.onCreate(MainActivity.kt:21)
```

### Observed behavior

When using a column chart to display related data for a single point on the x-axis (e.g. a single point in time, in epoch seconds), java.lang.IllegalArgumentException is being thrown. I've seen your [reply](https://github.com/patrykandpatrick/vico/issues/374#issuecomment-1764101945) to a similar issue, where you mentioned that using the same x value multiple times without any other x values will cause `calculateXGcd()` to fail, and while it makes sense for numbers that have a negligible difference, I don't think it should apply in this case.

Using exactly one entry works as expected:
```kotlin
val xValue = 123
chartView.setModel(ChartEntryModelProducer(listOf(entryOf(xValue, 5))).getModel())
```

Additionally, when using charts to display points in time that are too close (measured in seconds), `Float`s will lose precision and become the same value. Can we transition to `Double` entries?

### Expected behavior

`calculateXGcd()` should return a predefined value, with behavior being controlled by a boolean flag

### Vico version(s)

Latest unstable version

### Android version(s)

Tested on Android 13, but should apply to all versions

**Comment by patrickmichalik** [comment]
Hello! The error occurs because you have two `ChartEntry` instances with identical _x_ values in a single series. This violates the definition of a function. An _x_ value can appear multiple times in one data set, but not in one series, which must be a valid mathematical mapping. Please use two series.

Regarding switching to `Double`, this is something that we’ll be looking into for version 2, as many changes will be required. A workaround is described [here](https://github.com/patrykandpatrick/vico/issues/374#issuecomment-1764148646).

Because the behavior in question isn’t a bug, I’ll be closing the issue, but please feel free to comment if you have any questions.
