### ISSUE TITLE
MutableExtraStore is making tests fail

### ISSUE THREAD

**Issue by gusandrianos** [patrykandpatrick/vico#503]
### How to reproduce

Write a JUnit test comparing an expected and actual state of a `ChartEntryModel`.

### Observed behavior

While the data inside the expected and actual state is the same, the following difference is observed.

```
expected: extraStore=com.patrykandpatrick.vico.core.entry.diff.MutableExtraStore@66223d94
actual: extraStore=com.patrykandpatrick.vico.core.entry.diff.MutableExtraStore@173f1614
```

I believe the solution is to change `MutableExtraStore` to be a `data` class.

### Expected behavior

Since the contents of MutableExtraStore are the same, they should not make the tests fail.

### Vico version(s)

Latest stable version

### Android version(s)

14

### Additional information

Actually on version 1.13.0 but the version picker won't let me pick that.

**Comment by patrickmichalik** [comment]
Hello! Thanks for the report. We’ll look into this and release a bug-fix update.

Regarding the version selector, it’s limited to the latest stable version and the latest unstable version because only these two versions are supported. An issue affecting an older version may have already been resolved. Only if a bug still exists is a report of it actionable, and at least one of the two options in the list must apply in this case. The problem you’re reporting is present in version 1.13.1, making “Latest stable version” accurate. Had it been fixed in 1.13.1, we would ask you to update—it would be impossible for us to publish a release that comes between 1.13.0 and 1.13.1.

**Comment by patrickmichalik** [comment]
[Vico 2.0.0 Alpha 5](https://github.com/patrykandpatrick/vico/releases/tag/v2.0.0-alpha.5) addresses this. A fix will also be included in Vico 1.13.2, which is coming soon.

**Comment by patrickmichalik** [comment]
There’s been a small change of plans: the next stable version will be 1.14.0, not 1.13.2. This doesn’t change anything as far as the fix is concerned—the `ExtraStore` problem will, of course, be resolved. [Vico 1.14.0 Alpha 1](https://github.com/patrykandpatrick/vico/releases/tag/v1.14.0-alpha.1) includes the fix, and Vico 1.14.0 (stable) should be out soon, as no large changes are planned.

**Comment by gusandrianos** [comment]
@patrickmichalik I'll check it out, thanks for the quick fix and happy new year!

**Comment by patrickmichalik** [comment]
You’re welcome, and happy New Year to you too, @gusandrianos!

**Comment by patrickmichalik** [comment]
[Vico 1.14.0](https://github.com/patrykandpatrick/vico/releases/tag/v1.14.0) is rolling out. Cheers!
