### ISSUE TITLE
Cannot make a LabelFormatter on stacked column chart

### ISSUE THREAD

**Issue by matpascaud** [patrykandpatrick/vico#652]
### How to reproduce

Hi,
Since I updated to 2.0.0 Alpha 14, I do not have the correct label on top of each bar except for the first color. It displays 0 except for the first color (red)
So I have a list of list of entries, 3 lists since I have 3 colors. I assign a Y value as 0 for colors I do not want to render (red if >=20, yellow between 20 and 40 and green for > 40).
![Screenshot_20240409_094918](https://github.com/patrykandpatrick/vico/assets/534304/a8c61308-f7ab-4f31-9e4f-0e2b7980b804)

The label formatter is as below 
`        markerComponent.labelFormatter = MarkerLabelFormatter { markedEntries, chartValues ->
            val entry = markedEntries.first().entry as ColumnCartesianLayerModel.Entry
            String.format("%.0f", entry.y)
        }
`
I think the problem comes from the fact I am using first but I do not find a way to loop over all colors. 
Is it possible to get some help? Am I doing something wrong?
Thanks.

### Observed behavior

The marker label is incorrect except for the first color.

### Expected behavior

I should have correct labels for the 3 colors on stacked bar.

### Vico version(s)

Latest unstable version

### Android version(s)

31

**Comment by patrickmichalik** [comment]
Hello! We’ve recently resolved an issue affecting data labels in `ColumnCartesianLayer`s with `MergeMode.Stacked` applied. It looks like the bug made your `MarkerLabelFormatter` work when, in fact, it shouldn’t have worked. `first` appears to be the culprit here. Could you try switching to `first { it.entry.y != 0f }`?

By the way, [Vico 2.0.0 Alpha 13](https://github.com/patrykandpatrick/vico/releases/tag/v2.0.0-alpha.13) introduces column-by-column customization for `ColumnCartesianLayer`. The solution you’re using to give your columns different colors will, of course, continue to work, but I’d suggest switching to `ColumnProvider`.

Since this isn’t a bug, I’ll be closing the issue, but please feel free to comment if you have any questions.

**Comment by matpascaud** [comment]
For those who might be interested in how I implement the labelFormatter, here it is:
```
markerComponent.labelFormatter = MarkerLabelFormatter { markedEntries, chartValues ->
            val entries = markedEntries.filter {
                (it.entry as ColumnCartesianLayerModel.Entry).y > 0

            }
            if(entries.isEmpty())
                ""
            else {
                String.format("%.0f", (entries.first().entry as ColumnCartesianLayerModel.Entry).y)
            }

        }
```

**Comment by patrickmichalik** [comment]
Thanks for sharing, @matpascaud! It looks like I forgot to add `as ColumnCartesianLayerModel.Entry` after `it.entry` in my previous comment. I’ve updated the code snippet. Apologies for the error.

Seeing that only the first nonzero `ColumnCartesianLayerModel.Entry` is read here, I’d suggest using `first`, not `filter`. This will make the logic simpler and more direct. It will also improve performance and reduce memory use, though only marginally, as `markedEntries` is a short list. If it’s possible for all columns in a stack to have _y_ values of zero, `firstOrNull` can be utilized instead.

**Comment by matpascaud** [comment]
Thanks @patrickmichalik.
I upgraded to Alpha 16 and I must confess I do not know how to convert from the code above to the new API.
I need to display the value of the current colum and not all 3columns (3 colors).
There is no more access to Y value like in MarkerLabelFormatter ?

**Comment by patrickmichalik** [comment]
This should do the trick, @matpascaud:

```kt
CartesianMarkerValueFormatter { _, targets ->
    val target = (targets.first() as ColumnCartesianLayerMarkerTarget)
    "%.0f".format(target.columns.first { column -> column.entry.y != 0f }.entry.y)
}
```

That said, switching to `ColumnProvider`, which I touched on above, would be optimal. You’ll then no longer need a custom `CartesianMarkerValueFormatter`. If you have any questions or need an example, let me know.

**Comment by matpascaud** [comment]
Wow, that's quick! Many thanks.
I still need to modify because it's crashing probably when there is not colum but at least, I have an example.
I probably need switching to columnProvider. I have done part of it but probably not enough
```
with (chartView) {
            chart = CartesianChart(
                ColumnCartesianLayer(
                    columnProvider =
                    series(
                        columnColors.map { color ->
                            LineComponent(
                                color = color,
                                thicknessDp = 13f,
                                shape = Shape.Rectangle,
                            )
                        },
                    ),
                    spacingDp = 7f,
                    innerSpacingDp = 2f,
                    mergeMode =  { ColumnCartesianLayer.MergeMode.Stacked},
                    verticalAxisPosition = null,
                    dataLabel = null,
                    dataLabelVerticalPosition = VerticalPosition.Top,
//                    dataLabelValueFormatter = DecimalFormatValueFormatter(),
                    dataLabelRotationDegrees = 0f,
                    drawingModelInterpolator = DefaultDrawingModelInterpolator()
                )
```

**Comment by patrickmichalik** [comment]
You’re welcome, @matpascaud! It sounds like there are stacks in which all columns have _y_ values of zero. For such stacks, `first` will throw an exception. There are two ways of addressing this—the choice of approach depends on the desired result. When there’s no column, should the `CartesianMarker` be shown? If so, what should its label be?

Regarding `ColumnProvider`, what it enables you to do is switch from multiple series to just one and style individual columns based on their _y_ values. With one series, you won’t have any zero columns to ignore, and so a custom `CartesianMarkerValueFormatter` will no longer be needed. If you’re able to share the entirety of your Vico code, I’ll be happy to describe what changes are needed. Otherwise, I can prepare an example based on the screenshot you’ve shared.

**Comment by patrickmichalik** [comment]
You’re welcome, @matpascaud! I posted a reply a while ago, but I later noticed that it required clarification, so I deleted it. This is a more comprehensive revision.

For the `CartesianMarkerValueFormatter` above, I used `first`, which requires that each stack have a nonzero column. It sounds like your chart has all-zero stacks, which I previously wasn’t sure about. For such stacks, `first` will throw an exception. As discussed above, you can use `firstOrNull` to ensure that all-zero stacks are properly handled. The following `CartesianMarkerValueFormatter` should behave as expected and not produce any crashes. Sorry for the confusion.

```kt
CartesianMarkerValueFormatter { _, targets ->
    (targets.first() as ColumnCartesianLayerMarkerTarget)
        .columns
        .firstOrNull { column -> column.entry.y != 0f }
        ?.let { column -> column.entry.y.roundToInt().toString() }
        .orEmpty()
}
```

I’ve realized that even without the migration to `ColumnCartesianLayer.ColumnProvider`, the need for a custom `CartesianMarkerValueFormatter` can be avoided. As it stands, said `CartesianMarkerValueFormatter` is needed because there are extra columns with _y_ values of zero, and these columns are to be ignored. Migrating to `ColumnCartesianLayer.ColumnProvider` entails removing these columns, but as such, they can be done away with either way. That said, since the `ColumnCartesianLayer.ColumnProvider` migration would be beneficial regardless, I’d suggest using the `firstOrNull`-based `CartesianMarkerValueFormatter` above for now and then adopting `ColumnCartesianLayer.ColumnProvider` and removing the custom `CartesianMarkerValueFormatter`.

Here, the migration to `ColumnCartesianLayer.ColumnProvider` should involve switching from multiple series to one and creating a custom `ColumnCartesianLayer.ColumnProvider` implementation that styles individual columns based on their _y_ values. The resulting logic will be simpler and more flexible. For your chart, `ColumnCartesianLayer.ColumnProvider.series` should be avoided. If you’re able to share the entirety of your Vico code, I’ll be happy to describe how to migrate. Otherwise, I can prepare an example based on the screenshot you’ve shared and everything else we’ve discussed.

**Comment by matpascaud** [comment]
@patrickmichalik You really saved me hours of work trying to make the code doing what I expected. So big thanks again.
As soon as this part is fine, I think I will migrate to ColumnCartesianLayer.ColumnProvider to make the code more concise and clear.
I still have something a bit weird with this code: persistent marker appear at the top of the column only for the first color. 
```
val markerFormatter = CartesianMarkerValueFormatter { _, targets ->
            (targets.first() as ColumnCartesianLayerMarkerTarget)
                .columns
                .firstOrNull { column -> column.entry.y != 0f }
                ?.let { column -> column.entry.y.roundToInt().toString() }
                .orEmpty()
        }

        val markerComponent = DefaultCartesianMarker(label = markerTxtComponent, labelPosition = DefaultCartesianMarker.LabelPosition.AbovePoint, valueFormatter = markerFormatter)

```

**Comment by patrickmichalik** [comment]
Happy to help, @matpascaud. I took a look, and this turned out to be a bug on our end. I’ve resolved it and released a hotfix, [Vico 2.0.0 Alpha 17](https://github.com/patrykandpatrick/vico/releases/tag/v2.0.0-alpha.17). Could you try updating?

**Comment by matpascaud** [comment]
@patrickmichalik Thanks again, updating to [2.0.0 Alpha 17]( https://github.com/patrykandpatrick/vico/releases/tag/v2.0.0-alpha.17) solves the bug.

**Comment by patrickmichalik** [comment]
I’m glad to hear that, @matpascaud. My pleasure!
