### ISSUE TITLE
Feature Missing - Slide to Position

### ISSUE THREAD

**Issue by PythonVader** [patrykandpatrick/vico#691]
### How to reproduce

There isnt a clear way to slide to a certain position on the graphs plotted with vico
In compose, a lazy list would have a scroll state where you can specify an index at which an initial slide to that position will happen

### Observed behavior

No way to slide to position

### Expected behavior

Graph can dynamically have a position at which view should slide to

### Vico version(s)

Latest stable version

### Android version(s)

34

**Comment by PythonVader** [comment]
Very Poor Documentation,
No Support,

**Comment by Gowsky** [comment]
Hello @PythonVader. First of all, this is a feature request, and you've opened a bug report. A lack of a feature is not a bug.

Second of all, this feature is already available in Vico. Both Vico 1 and 2 have scroll state classes with programmatic scroll. If you're referring to scrolling to a certain x value, it was added in Vico 2. This is covered in the [wiki](https://patrykandpatrick.com/vico/wiki/cartesian-charts/hosts#scroll-and-zoom).

>Very Poor Documentation,

You're welcome to suggest improvements. However, I don't think you actually read it, otherwise, you'd be aware that this feature is available, and you'd know where to post feature requests. Every API is documented in the API reference.

>No Support,

Is it because you had to wait two days for an answer you could have found in the documentation? We respond to every issue and discussion, but we're volunteers and we can't provide instant 24/7 support. I'd like to point out that this is an open-source project provided to you free of charge, and you're not entitled to anything. We're open to feedback, but please, behave like an adult.

**Comment by Gowsky** [comment]
What do mean by "proper documentation"? The `ComposedChart` example is [here](https://patrykandpatrick.com/vico/wiki/1.14.0/basic-examples#composed-chart). More information about the chart is [here](https://patrykandpatrick.com/vico/wiki/1.14.0/charts#composedchart) and [here](https://patrykandpatrick.com/vico/wiki/1.14.0/handling-data).
