### ISSUE TITLE
Chart does not recompose when AxisValuesOverrider maxY is changed from 0 to greater than 0

### ISSUE THREAD

**Issue by rpaynetoast** [patrykandpatrick/vico#791]
### How to reproduce

On `columnChart`, set the `axisValuesOverrider` parameter to `AxisValuesOverrider.fixed(maxY = 0)`. Then toggle the `maxY` to a number greater than 0.

```kotlin
val initialEntries = listOf(
    listOf(FloatEntry(0.0f, 0.0f), FloatEntry(1.0f, 0.0f), FloatEntry(2.0f, 0.0f)),
)

val updatedEntries = listOf(
    listOf(FloatEntry(0.0f, 10.15f), FloatEntry(1.0f, 30.24f), FloatEntry(2.0f, 37.0f))
)

@Composable
fun FullSizedChart(
    modifier: Modifier = Modifier,
) {
    var entries by remember { mutableStateOf(initialEntries) }
    val chartEntryModelProducer = remember { ChartEntryModelProducer() }
    LaunchedEffect(entries) {
        chartEntryModelProducer.setEntries(entries)
    }
    Column(
        horizontalAlignment = Alignment.CenterHorizontally
    ) {
        val maxY = entries.flatten().maxOf { it.y }
        val axisValuesOverrider = AxisValuesOverrider.fixed(maxY = maxY)
        Chart(
            chart = columnChart(axisValuesOverrider = axisValuesOverrider),
            chartModelProducer = chartEntryModelProducer,
            endAxis = rememberEndAxis(),
            bottomAxis = rememberBottomAxis(),
            modifier = modifier
        )
        Button(onClick = {
            entries = if (entries == initialEntries) {
                updatedEntries
            } else {
                initialEntries
            }
        }) {
            Text(text = "Toggle chart")
        }
    }
}

```

### Observed behavior

Chart does not recompose:

https://github.com/patrykandpatrick/vico/assets/166438828/baae0154-6073-43af-b8d4-385fae77042f

### Expected behavior

Chart should recompose

### Vico version(s)

1.15.0

### Android version(s)

14

#### Workaround

If `maxY` is zero, set `axisValuesOverrider` to `null`. Set an `itemPlacer` on `bottomAxis` that toggles between 0 and a number greater than 0.

```kotlin
...

@Composable
fun FullSizedChart(
    modifier: Modifier = Modifier,
) {
    ...
        val axisValuesOverrider = if (maxY == 0f) null else AxisValuesOverrider.fixed(maxY = maxY)
        val maxItemCount = if (maxY == 0f) 0 else 4
        Chart(
            chart = columnChart(axisValuesOverrider = axisValuesOverrider),
            chartModelProducer = chartEntryModelProducer,
            endAxis = rememberEndAxis(
                itemPlacer = AxisItemPlacer.Vertical.default(maxItemCount = maxItemCount),
            ),
            ...
}
```

**Comment by Gowsky** [comment]
I'm reposting the comment as I forgot to add something important. 

First, with `ChartEntryModelProducer`, it's incorrect to swap a `Chart`'s `AxisValuesOverrider` this way. Instead, you should use a single implementation with dynamic behavior. This relates to the asynchronous behavior of `ChartEntryModelProducer` and the fact that `AxisValuesOverrider` is used during data updates. These topics are described in detail in the Vico 2 documentation. The API is a bit different, but the same principles apply. See ["`AxisValueOverrider`"](https://patrykandpatrick.com/vico/wiki/cartesian-charts/layers/#axisvalueoverrider) (particularly the warning box) and ["Asynchrony and extras."](https://patrykandpatrick.com/vico/wiki/cartesian-charts/data#asynchrony-and-extras) The correct approach in your case is to create an `AxisValuesOverrider` implementation like this:

```kt
object : AxisValuesOverrider<ChartEntryModel> {
    override fun getMaxY(model: ChartEntryModel) = // ...
}
```

Second, you can't set the maximum _y_ value to zero when the minimum _y_ value is also zero. Such a _y_ range would imply that the chart is zoomed in infinitely, which is impossible. This is the reason for the columns not being drawn.

**Comment by patrickmichalik** [comment]
Hello, @rpaynetoast! I wanted to share some further information.

The reason why the chart remains blank when `updatedEntries` and a nonzero maximum _y_ value are applied is that the initial, incorrect _y_ range causes persistent corruption. Since `DrawingModel`s are interpolated, one broken `DrawingModel` can cause subsequently generated ones to be invalid too. We’ll look into adding a check that throws an exception when the _y_ range is overridden incorrectly.

`AxisItemPlacer.Vertical` is the appropriate means of making a `VerticalAxis` blank. However, the `AxisItemPlacer.Vertical`-switching mechanism that you’ve shared may cause synchronization issues. Since `ChartEntryModelProducer` handles updates asynchronously, `entries` may not always match what’s displayed on the chart. No critical problems should arise, but you may observe minor glitches. For proper synchronization, such data-dependent changes should be handled via extras. Unfortunately, in Vico 1, switching to extras here would prove quite challenging. Even with a custom `AxisItemPlacer.Vertical` implementation, you’d run into the problem of the `ExtraStore` being unavailable in a few places. An exceeding number of overrides would be required. Thus, practically speaking, this use case requires Vico 2. Below is a quick example. Please note that overriding the _y_ range isn’t necessary.

```kt
val y1 = listOf(0, 0, 0)
val y2 = listOf<Number>(10.15, 30.24, 37)
val isEndAxisBlankKey = ExtraStore.Key<Boolean>()
val endAxisItemPlacer = AxisItemPlacer.Vertical.count({ if (it[isEndAxisBlankKey]) 0 else null })

@Preview
@Composable
fun Example() {
  var y by remember { mutableStateOf<List<Number>>(y1) }
  val modelProducer = remember { CartesianChartModelProducer() }
  LaunchedEffect(y) {
    withContext(Dispatchers.Default) {
      modelProducer.runTransaction {
        columnSeries { series(y) }
        extras { it[isEndAxisBlankKey] = y == y1 }
      }
    }
  }
  Column(modifier = Modifier.padding(16.dp), verticalArrangement = Arrangement.spacedBy(16.dp)) {
    CartesianChartHost(
      rememberCartesianChart(
        rememberColumnCartesianLayer(),
        endAxis = rememberEndAxis(itemPlacer = endAxisItemPlacer),
        bottomAxis = rememberBottomAxis(),
      ),
      modelProducer,
    )
    Button({ y = if (y == y1) y2 else y1 }) { Text("Update data") }
  }
}
```

[](https://github.com/user-attachments/assets/30251c83-4324-444f-948e-8e965c3a2208)
