### ISSUE TITLE
Chart does not correctly override axis values with `AxisValueOverrider` given two non-consecutive numbers

### ISSUE THREAD

**Issue by LeeWeeder** [patrykandpatrick/vico#822]
### How to reproduce

```kotlin
val modelProducer = remember { CartesianChartModelProducer() }
    LaunchedEffect(Unit) {
        val data = listOf(1, 3)

        modelProducer.runTransaction {
            lineSeries {
                series(
                    x = data,
                    y = data.indices.toList()
                )
            }
        }
    }
    
    CartesianChartHost(
        chart = rememberCartesianChart(
            rememberLineCartesianLayer(
                axisValueOverrider = remember {
                    // AxisValueOverrider
                    object : AxisValueOverrider {
                        override fun getMinX(minX: Double, maxX: Double, extraStore: ExtraStore): Double {
                            return 1.0
                        }

                        override fun getMaxX(minX: Double, maxX: Double, extraStore: ExtraStore): Double {
                             return 7.0
                        }
                    }
                }
            ),
            bottomAxis = rememberBottomAxis()
        ), modelProducer = modelProducer
    )
```

### Observed behavior

![Screenshot_20240731_155954](https://github.com/user-attachments/assets/ebe3f3ef-fbbb-401e-9c8d-df345fc1e304)

Given the default `itemPlacer`, some x values are missing.

In some cases, the max value will be missing.

![Screenshot_20240731_161407](https://github.com/user-attachments/assets/af38eaf8-e3d7-498e-917e-7a8272b973e5)

### Expected behavior

![Screenshot_20240731_160749](https://github.com/user-attachments/assets/d8d0dcd6-9fd3-4455-ae5e-ff81c84b1db4)

Given also the default `itemPlacer`, the x values were there, from 1 to 7.

> [!NOTE]
> I am using two consecutive numbers here because, with that, I can show the expected behavior. It will also work on more than two entries.

### Vico version(s)

2.0.0-alpha.25

### Android version(s)

34

**Comment by Gowsky** [comment]
This behavior is expected and is related to the _x_ step. To achieve the expected result please set the `xStep` to `1` via `rememberCartesianChart(getXStep = { 1.0 })`. We'll share a detailed explanation as soon as we can. We have a large volume of requests at the moment.

**Comment by Gowsky** [comment]
The API has changed, and this now works differently, but to provide a brief explanation for Vico `2.0.0-alpha.25`:

`AxisValueOverrider` is responsible for the _x_ and _y_ ranges, not for axis labels. These are related but not synonymous. In the second image under "Observed behavior," there is, in fact, room for an entry at _x_ = 7. The very left of the chart is _x_ = -1.5, and the very right is _x_ = 8.5. (This widened range is due to the use of `HorizontalLayout.Segmented`.) Thus, there's nothing for the `AxisValueOverrider` to do.

Labels are shown for _x_ = 1 and _x_ = 6 because the data's minimum _x_-value is 1, and the intrinsic _x_-step is 5. With `HorizontalLayout.Segmented`, a segment is added for each major _x_-value, and the segment width is equal to the _x_-step. This is why overriding the _x_-step to 1 produced the desired result. It is also the reason for the "missing" _x_-values you mentioned.

In the original setup, if you were to override the maximum _x_-value to one greater than _x_ = 8.5 (the right of the chart), then you'd see a difference. In accordance with the specification of `HorizontalLayout.Segmented`, a third segment would be added, and there'd be a new label for _x_ = 11. The right of the chart would now be _x_ = 13.5.
