### ISSUE TITLE
ANR called for basic line graph

### ISSUE THREAD

**Issue by joey101** [patrykandpatrick/vico#824]
### How to reproduce

[https://github.com/patrykandpatrick/vico/discussions/821#discussioncomment-10204599](url)

### Observed behavior

Causes ANR

### Expected behavior

Graph is meant to be there

### Vico version(s)

2.0.0-alpha.25

### Android version(s)

14

**Comment by Gowsky** [comment]
Hi @joey101, the crash is related to the timestamps being incorrectly calculated. From the code you've provided:

```kotlin
val staticDataX = listOf(
        LocalDateTime.now().minusMinutes(10).atZone(ZoneId.systemDefault()).toInstant()
            .toEpochMilli(),
        LocalDateTime.now().minusMinutes(8).atZone(ZoneId.systemDefault()).toInstant()
            .toEpochMilli(),
        LocalDateTime.now().minusMinutes(6).atZone(ZoneId.systemDefault()).toInstant()
            .toEpochMilli(),
        LocalDateTime.now().minusMinutes(4).atZone(ZoneId.systemDefault()).toInstant()
            .toEpochMilli(),
        LocalDateTime.now().minusMinutes(2).atZone(ZoneId.systemDefault()).toInstant()
            .toEpochMilli(),
        LocalDateTime.now().atZone(ZoneId.systemDefault()).toInstant().toEpochMilli()
    )
```

`LocalDateTime.now()` may be different between invocations. When this happens, the _x_ values aren't evenly spaced. For example, some pairs are spaced by 120K ms (2 min), and others are spaced by 199,999 ms. The _x_ step then becomes 1, which makes the chart content extremely wide (millions of pixels). Realistically, such a chart would be unusable.

Please correct the logic so that the reference timestamp doesn’t change:

```kt
val now = LocalDateTime.now()
val staticDataX = listOf(
    now.minusMinutes(10).atZone(ZoneId.systemDefault()).toInstant().toEpochMilli(),
    now.minusMinutes(8).atZone(ZoneId.systemDefault()).toInstant().toEpochMilli(),
    …
)
```

The chart will then behave properly.

If you had intermediate values, you could instead override the _x_ step and set it to 120K ms, but here, it seems like the aim is to have timestamps spaced by two minutes.

We’ll look into fixing the ANR regardless, but this is low-priority, since it occurs during incorrect usage that would generate an effectively infinite chart.

**Comment by joey101** [comment]
thank you works now for me, keep up the hard work this library is fun to use. @Gowsky

**Comment by Gowsky** [comment]
@joey101 You're welcome! I'm glad you enjoy it!
