### ISSUE TITLE
[BUG] Bottom axis item placer spacing doesn't affect ticks

### ISSUE THREAD

**Issue by tien** [patrykandpatrick/vico#826]
### How to reproduce

Use bottom axis item placer with custom spacing.

### Observed behavior

Tick appeared for all steps while label correctly respect spacing value.

### Expected behavior

Tick should only appear every `n` spacing.

### Vico version(s)

1.15.0

### Android version(s)

VanillaIceCream

### Screenshot

<img width="327" alt="image" src="https://github.com/user-attachments/assets/1f035813-3d2f-478c-9505-1da799ec67e0">

**Comment by patrickmichalik** [comment]
Hello! This behavior is expected. As described [here](https://patrykandpatrick.com/vico/api/1.15.0/core/com.patrykandpatrick.vico.core.chart.layout/-horizontal-layout/-segmented), with `HorizontalLayout.Segmented`—which is the default—ticks are displayed at the edges of the segments. Since the ticks aren’t tied to the labels, they’re unaffected by the label spacing. The tick positioning depends on the segment count, which in turn is influenced by the _x_ step.

To achieve the result you’re looking for, please apply `HorizontalLayout.FullWidth`. As per [its documentation](https://patrykandpatrick.com/vico/api/1.15.0/core/com.patrykandpatrick.vico.core.chart.layout/-horizontal-layout/-full-width), there will then be as many ticks as there are labels, and each tick will be directly above its label.

[The `AxisItemPlacer.Horizontal.default` documentation](https://patrykandpatrick.com/vico/api/1.15.0/core/com.patrykandpatrick.vico.core.axis/-axis-item-placer/-horizontal/-companion/default) appears to describe `spacing` somewhat imprecisely. This will be corrected.

**Comment by tien** [comment]
Thanks for the quick response @patrickmichalik, please close this issue or use it to track documentation around `spacing`, which ever make sense to you 🙏.

**Comment by patrickmichalik** [comment]
You’re welcome! We plan on using it to track the documentation update—I’ve applied the “documentation error” label. Cheers!

**Comment by tien** [comment]
Thank you sir, just bought you a ☕️. Keep up the great work!

**Comment by patrickmichalik** [comment]
Thanks a lot for your support, @tien!

**Comment by patrickmichalik** [comment]
The documentation inaccuracy has been addressed in [Vico 2.0.0 Beta 1](https://github.com/patrykandpatrick/vico/releases/tag/v2.0.0-beta.1) (which includes related API changes) and [Vico 1.16.0 Alpha 1](https://github.com/patrykandpatrick/vico/releases/tag/v1.16.0-alpha.1).

**Comment by patrickmichalik** [comment]
[Vico 1.16.0](https://github.com/patrykandpatrick/vico/releases/tag/v1.16.0) is now available.
