### ISSUE TITLE
Line renders both `topFill` & `bottomFill` colors for negative data

### ISSUE THREAD

**Issue by mak1nt0sh** [patrykandpatrick/vico#835]
### How to reproduce

```
fill = LineCartesianLayer.LineFill.double(
                            topFill = fill(MaterialTheme.colorScheme.primary),
                            bottomFill = fill(MaterialTheme.customColors.negative)
                        )
```

Data for this view:

```
xSeries = [19936, 19937, 19938, 19939, 19940, 19941, 19942]
ySeries = [500.00, -5, -5, -5, -5, -25, -25]
```

### Observed behavior

![lineissue](https://github.com/user-attachments/assets/20c10a06-d7fd-45c4-b888-ff4c5e755aee)

Line colors are split and default marker mixes the colors of both fill colors

### Expected behavior

The color of the line and marker should be distinct for positive/negative values.

### Vico version(s)

2.0.0-alpha.27

### Android version(s)

Any

**Comment by Gowsky** [comment]
Hi @mak1nt0sh, you seem to describe an additional issue here compared to [your comment](https://github.com/patrykandpatrick/vico/issues/784#issuecomment-2273528462). The comment mentioned the marker problem, but here you've also described that the _y_ = -5 line segment has split colors. With a single horizontal split it's geometrically impossible for it to never occur as the line has some thickness.

Here's the current state. 
![image](https://github.com/user-attachments/assets/eadb6ea7-a2f2-4f64-9179-1be196c26cb4)

For the _y_ = -5 line segment to not be split we'd have to shift the split upward. But then we'd be back to the problem described in #784.
![image](https://github.com/user-attachments/assets/9a67aa24-4457-458c-a316-3c1cb7cc84b8)

A possible solution would be to split the line vertically. Is it what you expect?
![image](https://github.com/user-attachments/assets/632af6e7-a10f-46aa-b8f5-db6acd3a9201)

**Comment by mak1nt0sh** [comment]
Can't it always draw above or below the threshold line? Anything above or equal to the splitY value would push the line to draw on the border and if <splitY draw below?

Sorry I'm on my phone rn, can't draw these beautiful sketches <3

**Comment by mak1nt0sh** [comment]
Can't it always draw above or below the threshold line? Anything above or equal to the splitY value would push the line to draw on the border and if <splitY draw below?

Sorry I'm on my phone rn, can't draw these beautiful sketches <3

Edit:

I guess it would require shifting the line by small offset equal to half the line width?

**Comment by mak1nt0sh** [comment]
Also the [#809](https://github.com/patrykandpatrick/vico/issues/809) is still not fixed.

<img width="444" alt="Screenshot 2024-08-09 at 14 38 56" src="https://github.com/user-attachments/assets/ccf36f53-573f-4f2f-9bff-59694d133eaf">

The bottom (negative line) is completely drawn with topFill.

Data for this view:

```
[19936, 19937, 19938, 19939, 19940, 19941, 
[500, 500, 500, -2, -2, -2, -2, -2, -202]
```

**Comment by Gowsky** [comment]
>Can't it always draw above or below the threshold line? Anything above or equal to the splitY value would push the line to draw on the border and if <splitY draw below?

In this case, the position of the line wouldn't reflect the data and there would be misalignments with axis guidelines, `HorizontalLine`s, other layers, etc.

>Also the https://github.com/patrykandpatrick/vico/issues/809 is still not fixed.

I believe it is.

>The bottom (negative line) is completely drawn with topFill.

It's not. If you zoom into the line you can see it starts fading to red.
<img src="https://github.com/user-attachments/assets/04c39304-6932-4790-b2aa-330240d13bab" width=100/>

You don't see the pure red, because the sliver is less than a pixel in height. In a high enough resolution, you'd see this.
<img src="https://github.com/user-attachments/assets/129d2a42-a233-443d-870a-00a880d7ee8c" width=100/>

It's the same story as above. The current state.
![image](https://github.com/user-attachments/assets/d53e43a1-096b-4953-a5b5-23c397bbdbce)

Again, for the _y_ = -2 line segment to be fully red we'd have to move the split upwards and we would be back to the issue #784.
![image](https://github.com/user-attachments/assets/b718fa69-589f-42b8-b41e-12ca6a83b399)

Once again, it would require vertical splits.

**Comment by mak1nt0sh** [comment]
I just checked a few apps like Yahoo finance and CoinMarketCap and it seems they both have different rendering ways. I guess I'll leave it up to you to decide the best way to go forward.

Yahoo seems to render by direction and stack the lines:

![markup_1000000751.png](https://github.com/user-attachments/assets/e23e9128-3195-4379-9e9a-e06bee1a246a)

CoinMarketCap splits by x:

![Screenshot_20240810-192919.png](https://github.com/user-attachments/assets/70b8e239-e451-4c22-8471-0eb1a80b17b5)

**Comment by mak1nt0sh** [comment]
Is more information needed? (I can see the label for this issue). 
I'm currently stuck on `2.0.0-alpha.22` due to this issue.

**Comment by Gowsky** [comment]
Sorry for the wait. Regarding the color mixing problem, we have all the required information for now. We will look into fixing this.

Regarding the edge case with the splits:
>Yahoo seems to render by direction and stack the lines:

This is slightly suboptimal, because with round caps, the split positioning is a bit imprecise, and with butt caps gaps can appear.

>CoinMarketCap splits by x:

The charts don't seem to be zoomable, or pannable so we weren't able to see how the splitting works. But we checked TradingView and it seems to use vertical splits.

![vertical splits](https://github.com/user-attachments/assets/cb3cd8a5-6e16-4dca-bc42-1132e35e9edc)

This is what I mentioned above, and it seems to be the best choice. We'll look into implementing this. However, this is an enhancement and not a bug fix. 
`AreaFill.double` now works as documented, even if it’s not suited for the edge case in question. Therefore, we’ll use this issue to track the color mixing problem, and we’d ask you to open a discussion in the “Ideas” category for the switch to vertical splits. It’s fine to just link this issue.

**Comment by mak1nt0sh** [comment]
Please also check [CoinMarketCap](https://coinmarketcap.com/) they handle horizontal splits pretty well. You can export graphs by clicking ... menu at the top right corner of the chart.

<img width="448" alt="Screenshot 2024-08-22 at 10 00 38" src="https://github.com/user-attachments/assets/fd40a419-9272-46ea-a28d-54ef1ab081b9">

**Comment by Gowsky** [comment]
[Vico v2 0.0-beta.4](https://github.com/patrykandpatrick/vico/releases/tag/v2.0.0-beta.4) fixes the color mixing.

**Comment by robertlinsener** [comment]
@Gowsky How can I split it vertically? So color depends on x-value, not on y-value?

**Comment by Gowsky** [comment]
Hello, @robertlinsener. This can be achieved with a custom `LineCartesianLayer.LineFill` implementation. `CartesianDrawingContext.getVisibleXRange()` extension function might be useful, if your chart supports scrolling. The function is `internal`, but can be copied over if necessary. In some cases, you can also achieve this by using multiple series. If you have any specific questions, please create a new discussion, as it's a separate topic.
