### ISSUE TITLE
Can't figure out how to do anything

### ISSUE THREAD

**Issue by jameskellie** [patrykandpatrick/vico#851]
### Area

Data, Legends

### Error

The docs are so vague that as someone new to Kotlin but with over 5 years of C++/C#/Java experience, I cannot figure out how to do anything with this library. How do I prevent the Y axis from starting at 0? How do I enter custom data? Why isn't there a simple "addDataPoint()" function?

I have downloaded and ran the sample project, which as about 50 million files dispersed through kotlin and xml. It is so complex and convoluted that just copy/pasting one of the charts and getting it to build in my own project was a nightmare in itself. I'm thinking back to my C++ days of using Dear Imgui, where there was 1 sample cpp file with everything you needed and I'm sorely missing that level of clear, consice documentation here with this library.

To add my own data, the docs only state "Data updates are run via runTransaction". Ok... So how do I use it then? I have a List<> of data points, how do I feed it to this runTransaction function so that they are added to the graph? That's kind of the most important part that the docs should go over, yeah? The sample code does some lineSeries() function call with a nested series() function and what looks like a map declaration with random variables? It's so convoluted that I have no idea what that's going on internally. I don't know what any of these library functions do because you don't have them documented, I don't know how I'm meant to change this code to insert my own list of data into the chart.

I just want a simple chart that I can make in less than 10 lines of code, that has custom data and a y axis that isn't stuck starting at 0.

**Comment by Gowsky** [comment]
> The docs are so vague that as someone new to Kotlin but with over 5 years of C++/C#/Java experience, I cannot figure out how to do anything with this library.

Knowledge of Kotlin and Android development is a prerequisite. Our documentation isn't a guide for either of those. I'd suggest focusing on specific issues rather than invoking your experience with other languages.

> How do I prevent the Y axis from starting at 0? How do I enter custom data?

This is answered in the wiki. Feel free to open a discussion in the "Questions" category if you need assistance.

> Why isn't there a simple "addDataPoint()" function?

That would be insufficient. I'm not sure what class you're referring to, but such a function wouldn't cover multiple series, combo charts, transaction atomicity, etc. Still, adding data to a basic chart is one line of code.

> dispersed through kotlin and xml. It is so complex and convoluted that just copy/pasting one of the charts and getting it to build in my own project was a nightmare in itself.

This dispersion between Kotlin and XML is characteristic of the view system and has nothing to do with Vico. If working with multiples files is an issue, you can always use Jetpack Compose, which is all-Kotlin and which Vico also supports. You can then transfer a sample chart by copying from one file.

> I'm thinking back to my C++ days of using Dear Imgui, where there was 1 sample cpp file with everything you needed and I'm sorely missing that level of clear, consice documentation here with this library.

These are two completely different environments. You can't possibly make a one-file Android sample app. Again, this has nothing to do with Vico.

> To add my own data, the docs only state "Data updates are run via runTransaction". Ok... So how do I use it then? I have a List<> of data points, how do I feed it to this runTransaction function so that they are added to the graph? That's kind of the most important part that the docs should go over, yeah?

"Yeah." And they do.

> The sample code does some lineSeries() function call with a nested series() function and what looks like a map declaration with random variables?

It generates a list of random numbers and passes it to `series` as an argument. `runTransaction` is based on a Kotlin DSL.

> It's so convoluted that I have no idea what that's going on internally.

This is basic Kotlin, but simpler examples can be found in the wiki.

> I don't know what any of these library functions do because you don't have them documented,

All of them are documented.

> I don't know how I'm meant to change this code to insert my own list of data into the chart. I just want a simple chart that I can make in less than 10 lines of code, that has custom data and a y axis that isn't stuck starting at 0.

The wiki includes minimal starters that can be easily copied and include only essential code. I suggest referring to those. As I said, the _y_-axis question is answered in the wiki, but again, you're welcome to open a discussion in the "Questions" category. The result you're looking for can be easily achieved.

Your rude, entitled behavior toward volunteers providing a free product is unacceptable. It's made even worse by the inaccuracy of your comments. Since none of the points you've raised is simultaneously related to Vico and true, I'm closing this issue.

**Comment by no-scope** [comment]
Yeah idk why they didn't make it like matplotlib which literally just works. I am done with kotlin too. going back to python.

**Comment by Gowsky** [comment]
> Jesus. You got hurt by a newcomer expressing himself. How big is your ego?

No, I simply noted that your behavior is inappropriate. You're free to express yourself, but you should do so politely.

> I think you need to take a step back and realise that if someone tells you that your docs are not clear enough for them, then that is a statement based upon a fact

Not all facts are particularly relevant. It may be a fact that one has little Kotlin experience, but that doesn't mean we should explain Kotlin's syntax in our documentation.

> and your response should be to understand where they got lost.

It's your responsibility to back up your comments. A rude complaint based on verifiably false assertions is neither actionable nor deserving of anyone's time.

> Instead, you've projected your subjective opinion by replying "nuh-uh, you're wrong and mean!"

It's not subjective that many of your comments are untrue. Once again, it's on you to provide evidence, not on me to disprove baseless claims, but for completeness, here's an example: in the context of `lineSeries`, you said, "I don't know what any of these library functions do because you don't have them documented," yet `lineSeries` is explicitly mentioned [here](https://patrykandpatrick.com/vico/wiki/cartesian-charts/layers/line-layer#data). As for you being impolite, I think it's a fair assessment.

> Brother, click on "Cartesian charts > Data" on your wiki and you'll find there is no code on that page that you can copy into a project to set the data of a chart.

I never said the information was on that page. I said it was in the wiki.

> It was only after making this issue that I found out you have to go to "Layers > Chart Type" to see real code examples.

This shows that the aforementioned information is, in fact, in the wiki.

> You know why I didn't figure that our prior to posting? Because the docs are poorly designed.

A single person's experience isn't definitive proof of poor documentation design. There's no shortage of readers who did figure it out, most likely because it's explicitly stated on the page in question: "How data is added to a `Transaction` depends on the `CartesianLayers` in use, so we cover this topic on the 'Candlestick layer,' 'Column layer,' and 'Line layer' pages." A specific suggestion for improvement would be more helpful than such blanket statements.

> Why on earth isn't inputting data under the "Data" heading?

For the reason explained in the quote above.

> What does "Layers" even mean in this context?

It refers to `CartesianLayer`s.

> To anyone other than you it's quite clear that the docs are not that well laid out.

You have no evidence that everyone believes so. In fact, you've not shared evidence of _anyone else_ believing so. Once again, a single person's experience isn't universal.

> You don't see the problem because you wrote the damn thing.

I don't see a problem because it's not been demonstrated.

> Not only that, but you're in denial!

Of what? At no point did I call the documentation clear or unclear. I simply noted that the points you raised were false.

> How can you say that in good faith when your docs look like this:

You've manipulated the code snippet. The newlines are there because there are multiple `series` calls. For a basic case, a single line is sufficient:

```kt
cartesianChartModelProducer.runTransaction { columnSeries { series(1, 8, 3, 7) } }
```

A more realistic case would involve a variable:

```kt
cartesianChartModelProducer.runTransaction { columnSeries { series(someList) } }
```

These lines are well within standard length limits, and they're exactly what `ktfmt` produces.

> But in that case I suppose every code file ever written is 1 line, right?

Certainly, but the line would not be within standard length limits. I belive it's clear that "one line" refers to a line of a reasonable length.

> It's quite clearly 3 lines to add data

It's three lines in the example from the wiki, which I never said I was referring to. As you can see above, in a basic case, it's one line, as I initially said.

> Or maybe it's just hidden somewhere else in the docs like this was.

I think it's an exaggeration to suggest that something with a dedicated section on one of the wiki's 18 pages is "hidden," especially when an ealier page links to the section.

> What few code examples you do provide are hyper specific to the use case that you provide. You typically don't give general use examples of how to manipulate the charts. If you have a use case outside of what you used in the docs, well, you're SOL. Enjoy spending a few hours backwards engineering a solution.

You've not provided any evidence of this being the case.

> When I go to a docs page I expect to see the following:

All of this is documented, except for the second point, since there's no dedicated function for adding data point by point (for the reasons described in my previous comment). Of course, you can add values one by one to a `List` and then pass it to `series`, but that's basic Kotlin, not a Vico feature.

> Instead, you went the route of "Here's a dump of all the code you need for a hyper-specific graph with predetermined data that I think looks cool. You're smart, you can figure the rest out."

Once again, you've not shared any evidence of this.

> You can look at this issue as constructive

There's nothing constructive about it. You've not shared any specific suggestions.

> or you can have a winge to your friends about how mean I was.

I think your behavior speaks for itself.

> Your call little man.

This aptly summarizes the tone of your comments. I doubt you'd feel the need to act this way if you had legitemate points to make.

Moving on to the Matplotlib point:

> Yeah idk why they didn't make it like matplotlib which literally just works. I am done with kotlin too. going back to python.

> If you compare to Matlab or Python he's just going to say "These are two completely different environments."

Yes, Matplotlib is a different library that runs in a different environment and serves a different purpose. Whereas Matplotlib synchronously generates static chart images, Vico is used for creating interactive, dynamically updated charts with asynchronous data processing. There is a whole host of requirements and constraints that apply to Vico but not to Matplotlib, so the APIs must be different.

> Meanwhile my app is indeed 1 kotlin file.

I said "one-file," not "one-Kotlin-file." One Kotlin file is possible, but then either the app is very basic, or the file is overly long. As far as Kotlin files go, the sample app has multiple charts, and having each chart in a separate file improves organization.

> We should instead compare to the JetBrains Kandy library

Kandy is the Kotlin equivalent of Matplotlib. It may use the same programming language as Vico, but just like with Matplotlib, the environment and purpose differ. That's why you can't use Kandy in an Android app. Incidentally, Kandy uses the term "layers," which you mentioned above, in the same way as Vico.

> which seems to do what this developer claims to be impossible

I used the term "insufficient," and I did so in the context of Vico and its requirements and constraints, not every library and every environment available.

> Yet here's this guy spouting how it's not possible to have one function do that because "That would be insufficient."

That's not what I said at all. I was referring to the `addDataPoint` function you brought up. Kandy doesn't have such a function either. Generally, Kandy's data-adding mechanism is very similar to Vico's.

Kandy:

```kt
plot {
    bars {
        x(listOf(...))
        y(listOf(...))
    }
}
```

Vico (formatted to span multiple lines for similarity with the Kandy sample):

```kt
modelProducer.runTransaction {
    columnSeries {
        series(x = listOf(...), y = listOf(...))
    }
}
```

> He's clearly one of those programmers that needs complexity and obfuscation to hide their fragile ego.

If the amount of evidence were anywhere close to the number of banal insults, we'd have a productive conversation.

> Using "free software" as a brittle shield while claiming to be some poor little "volunteer" is laughable. Pretty backwards to think you're so high and mighty that you're beyond criticism.

This misrepresents my comment. Critical feedback is welcome, but it should be productive. Your unconstructive, hostile approach would be inappropriate in any setting, but it's particularly appalling given the nature of the project. You _chose_ to take a look at this free library that I _chose_ to publish. There's nothing vaguely appropriate about attacking me because the documentation is structured differently than you'd like. I owe you nothing. [Open-source is not about you.](https://gist.github.com/richhickey/1563cddea1002958f96e7ba9519972d9)
