### ISSUE TITLE
LineCharts throw IllegalArgumentException in Compose Previews

### ISSUE THREAD

**Issue by mahoganykilo** [patrykandpatrick/vico#856]
### How to reproduce

Check Example app previews for ample evidence.

Android Studio Koala | 2024.1.1 Patch 1
Build #AI-241.18034.62.2411.12071903, built on July 10, 2024
Runtime version: 17.0.11+0-17.0.11b1207.24-11852314 aarch64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 14.6.1
GC: G1 Young Generation, G1 Old Generation
Memory: 8192M
Cores: 10
Metal Rendering is ON
Registry:
  idea.ignore.disabled.plugins=true
Non-Bundled Plugins:
  wu.seal.tool.jsontokotlin (3.7.4)
  com.github.copilot (1.5.17.6356)
  com.suusan2go.kotlin-fill-class (1.0.23)
  com.getyourguide.paparazzi (1.2.2024.1)

### Observed behavior

![image](https://github.com/user-attachments/assets/50266d1e-b2e3-407e-8fd3-7a3cd1023069)

### Expected behavior

Not throwing an exception

### Vico version(s)

2.0.0-alpha.28

### Android version(s)

n/a

**Comment by Gowsky** [comment]
Hi @mahoganykilo. This appears to be a bug in the Compose preview renderer. The `Canvas` initially has an incorrect size (0 by 0), while `DrawContext.size` reports the expected size. We will add a check for this and prevent the crash from happening, but since it's not actually a bug on our end, I'm closing this issue.

**Comment by Gowsky** [comment]
Hi @mahoganykilo. We've added a check that works around this renderer problem. It's available in [Vico 2.0.0 Beta 1](https://github.com/patrykandpatrick/vico/releases/tag/v2.0.0-beta.1).
