### ISSUE TITLE
Dynamically Removing a LineCartesianLayer Crashes

### ISSUE THREAD

**Issue by Tyler-Lopez** [patrykandpatrick/vico#914]
### Background

I posted [this same issue before](https://github.com/patrykandpatrick/vico/discussions/895#discussioncomment-10801045) as a Discussion Question. A point was made which at the time, made sense to me. This point was that, regardless of the error, the approach I was taking was unnecessary - I should not be dynamically adding or removing LineCartesianLayer.

However, I no longer feel this is unnecessary. So, I am opening this as a Bug - I think that is more correct than the original Question.

The problem is that you get the following crash when you dynamically remove a LineCartesianLayer. 

**Crash:** https://gist.github.com/Tyler-Lopez/b8feff82b168366f3b1e5d3b2cce66f6

> java.lang.ClassCastException: com.patrykandpatrick.vico.core.cartesian.layer.LineCartesianLayer cannot be cast to com.patrykandpatrick.vico.core.cartesian.CartesianChart

**Reproducible Minimal Example:** https://gist.github.com/Tyler-Lopez/0358e74977973034b7559ae7a172114b**

### Motivation For Why This Should Work

* The error is NOT reproducible when a ColumnCartesianLayer is dynamically removed. That can be tested by hitting the second switch in the above example.

* It is an expected competency to be able to nest a bar chart between two lines. If those two lines must share the same layer to avoid this crash when one is removed, it is not possible to do this.

### Other Note

I would love if, when cartesian layers were added & removed, they did not "reset" the chart. That is one really nice benefit to only use a single `LineCartesianLayer`: when you add and remove series from it, it doesn't reset the chart, it just animates in or out that one series.

### Demo

https://github.com/user-attachments/assets/4d256212-0c18-42ea-a178-687e242fe652

### Observed behavior

Removing (but not adding) a LineCartesianLayer crashes.

### Expected behavior

Removing a LineCartesianLayer should not crash, like how the ColumnCartesianLayer removal doesn't crash.

### Vico version(s)

2.0.0-beta.1

### Android version(s)

33

**Comment by Tyler-Lopez** [comment]
Oh - and I want to mention: that my minimum reproducible example is extremely simplified. I want to get ahead of a previous comment/question which was: 

> Why is this necessary? The layer won't be drawn if there's no data for it.

So, why is it necessary to remove a line cartesian layer dynamically?

It is necessary if the inputs themselves are completely dynamic. In my minimal example, they are over-simplified and not dynamic - so you could just leave the layers without removing them.

However, imagine if the parameter to the chart was just a list of "data series", like `List<Triple<Double, Double, DataSeriesType>>` where `DataSeriesType` could be a `COLUMN` or `LINE`.

In that case, when you update the list to remove a line, you have no choice but to remove the layer with it.

If this is confusing just let me know and I can write out a full example along these lines.

**Comment by Gowsky** [comment]
Hello, @Tyler-Lopez. This is a Jetpack Compose bug. `remember(*a)` fails when the size of `a` changes. (But when additional keys are added after `*a`, it works.) It happens to be the case that in the next version, as part of some unrelated changes, more keys will be added. Thus, the crash will stop occurring.

However, this isn't particularly relevant, because your API usage doesn't fulfill the requirements discussed [here](https://patrykandpatrick.com/vico/wiki/cartesian-charts/data/#asynchrony-and-extras) and is thus incorrect. As a result, you may still experience other issues when the crash no longer occurs. Currently, there's no API that would facilitate the required synchronization here — an `ExtraStore` lambda (or similar) would be required, and `layers` is just a `vararg` at the moment. This means that the API doesn't support your use case yet. Please open a feature request for a synchronized system for adding and removing `CartesianLayer`s.

> I would love if, when cartesian layers were added & removed, they did not "reset" the chart. That is one really nice benefit to only use a single `LineCartesianLayer`: when you add and remove series from it, it doesn't reset the chart, it just animates in or out that one series.

Once dynamically adding and removing `CartesianLayer`s is supported, this will be ensured.[^1]

Since this isn't our bug, and more importantly, it happens only when the API is misused, I'm closing the bug report. It is enough to link this issue in the feature request.

[^1]: The lack of a synchronized system for adding and removing `CartesianLayer`s is synonymous with dynamically adding and removing `CartesianLayer`s not being supported because, unlike in some other cases, there's no reasonable use case for adding and removing `CartesianLayer`s without synchronization with the data. When you need to show or hide a given layer for reasons other than a change in the available data, you should run a `Transaction` that adds or removes the appropriate data set. In this case, the animation works as desired.

**Comment by Tyler-Lopez** [comment]
Thanks so much for the reply, @Gowsky! Apologies, I was not aware of that issue with Compose. I appreciate the documentation linked.

I do have one question for the feature request to be more informed. It isn't that a synchronized system is needed for just adding and deleting `LineCartesianLayer` dynamically, right? I believe we also need a synchronized system for anything to do with modifying layers.

For example, I expect [this example of](https://gist.github.com/Tyler-Lopez/a13b5efa6235182b6862c8f69cae63bc) dynamically adding and removing `LineCartesianLayer.Line` within `LineCartesianLayer.LineProvider.series` is also a violation of the API.

My observations would agree with that where if I remove a `LineCartesianLayer.Line` from a chart with two lines, I see the second set of line data momentarily take the style of the first `LineCartesianLayer.Line` before the data is removed from the chart. This makes sense to me as the `LaunchedEffect` processes _after_ the `layers` parameter is updated to remove the `LineCartesianLayer.Line`.

**Comment by Tyler-Lopez** [comment]
Here is a demonstration of that, with a still-frame showing the doubling of the same `LineCartesianLayer.Line` for the 2nd line series as it exits. I believe this to be related and so will include it in the feature request.

https://github.com/user-attachments/assets/f0dee1a7-53b7-4f11-aade-48ab5d442fdb

![Screenshot 2024-10-11 at 2 10 40 PM](https://github.com/user-attachments/assets/eb7364b7-fb4d-4869-8d6e-3ffd516d4735)

**Comment by Gowsky** [comment]
>It isn't that a synchronized system is needed for just adding and deleting LineCartesianLayer dynamically, right? I believe we also need a synchronized system for anything to do with modifying layers.

Yes, that's right. In fact, as described in the wiki, it's required for any kind of dynamic setup tied to data updates. However, it already exists for other properties. That's why I explicitly mentioned dynamically removing and adding layers. 

>For example, I expect [this example of](https://gist.github.com/Tyler-Lopez/a13b5efa6235182b6862c8f69cae63bc) dynamically adding and removing LineCartesianLayer.Line within LineCartesianLayer.LineProvider.series is also a violation of the API.

Correct, but there's already a synchronized system available for this. 

@patrickmichalik will share more details soon.

**Comment by Tyler-Lopez** [comment]
I made this discussion so that the useful solution from Patrick wouldn't get lost in this issue, rather than bump for it https://github.com/patrykandpatrick/vico/discussions/924

**Comment by patrickmichalik** [comment]
I’ve responded there, @Tyler-Lopez.
