### ISSUE TITLE
The chart does not scroll forward when updating data every 100 milliseconds, but it works when updating every 1 second.

### ISSUE THREAD

**Issue by larrystephte** [patrykandpatrick/vico#966]
### How to reproduce

1. I have posted the relevant ViewModel and Compose code in this [gist link](https://gist.github.com/larrystephte/854f5d435e84b7ced252f426d11f39bd).
2. I wrote a program to simulate sending data every 100 milliseconds or every second.

### Observed behavior

![20241203151550](https://github.com/user-attachments/assets/879a2df5-5cb2-4d2c-a6e3-da1fb32d5315)
As shown in the image, whenever data is sent every 100 milliseconds, the graph gets stuck between 6 and 7 seconds and stops scrolling. However, when data is sent every second, the graph scrolls normally. So, I suspect something is causing it to freeze.

The x-axis values are as follows:[0.0, 0.3, 0.4, 0.7, 0.9, 1.0, 1.3, 1.5, 1.6, 1.8, 2.1, 2.2, 2.4, 2.6, 2.9, 3.0, 3.3, 3.5, 3.6, 3.9, 4.1, 4.4, 4.5, 4.8, 5.0, 5.1, 5.4, 5.6, 6.0, 6.0, 6.2, 6.5, 6.6, 6.8, 7.1, 7.2, 7.4, 7.5, 7.7, 7.8, 8.0, 8.1, 8.3, 8.4, 8.6, 8.8, 8.9, 9.1, 9.2, 9.4, 9.5, 9.7, 9.8, 10.0, 10.1, 10.3, 10.4, 10.6, 10.7, 10.9, 11.0, 11.2, 11.3, 11.5, 11.6, 11.8, 11.9, 12.1, 12.2, 12.4, 12.5, 12.7, 12.8, 13.0, 13.1, 13.3, 13.4, 13.6, 13.7, 13.9, 14.0, 14.2, 14.3]
The x-axis values go up to 14.3, but the chart still stops around 6 seconds.

### Expected behavior

1.The graph scrolls normally.
2.The x-axis still shows coordinates even when there is no data. Is it possible to display the coordinates only where there is data, or display them only at integer seconds? Thank you.

### Vico version(s)

2.0.0-beta.3

### Android version(s)

14

### Additional information

kotlin = "1.9.0"
vico = "2.0.0-beta.3"

**Comment by larrystephte** [comment]
Im sorry for the late response.I have solved the problem using your suggestion of receiving the CartesianChartModelProducer from the ViewModel  and transmitting data from the Viewmodel.Since the series must receive a list, i had to combine the lists in the Viewmodel.However, I have a question: why cant the series accept a single entry?In a real-time scenario with 100Hz or 1000Hz frequency, the list grows quickly, which could lead to performance issues.To address this, I optimized my data flow to support backpressure and prevent out-of-memory errors.

**Comment by Gowsky** [comment]
Could you be more specific?

> the list grows quickly

This would still be the case if the library had a dedicated API for appending entries. The only difference would be that the growing list would be in the library instead of in the `ViewModel`, giving you less flexibility.
 
> I optimized my data flow to support backpressure 

This also seems unrelated to the appending API you mentioned. Backpressure relates to the frequency of emissions. Regardless of how new entries are added, the speed at which they're added may be excessive, and backpressure may be needed.

> and prevent out-of-memory errors

What kind of out-of-memory errors exactly? What are they related to, and how would the appending API prevent them?

Generally, it seems like two things might make sense here:

- Decreasing the update rate. 1000 Hz significantly exceeds the screen refresh rate, so it doesn't make sense to try to run updates so frequently.
- Having a maximum size for the list instead of letting it grow forever. Once it reaches the maximum size, you can remove the oldest entry when adding a new one.

Neither of these seems to be related to the appending API, and the existing way of adding entries lets you implement these solutions (or any other one) easily.

**Comment by larrystephte** [comment]
Thank you for your response. 
> This would still be the case if the library had a dedicated API for appending entries.

Yes, I realize that too. Even if you provide an appending API, you would still need to handle these considerations. However, similar to [MPAndroidChart](https://github.com/PhilJay/MPAndroidChart), having less flexibility can help reduce complexity for users. 

> Decreasing the update rate. 1000 Hz significantly exceeds the screen refresh rate, so it doesn't make sense to try to run updates so frequently.
> Having a maximum size for the list instead of letting it grow forever. Once it reaches the maximum size, you can remove the 
oldest entry when adding a new one.

You are absolutely right. I am already implementing these practices.

I do have a question, though. While reviewing the source code of the Vico chart library, I noticed that every time runTransaction is called, it triggers a full update rather than an incremental update. Is this correct? If so, wouldn't this approach impact performance when the update frequency is high, such as updating 100 times per second? Every update triggers a complete redraw of the chart or view, which could lead to UI lag or excessive computational load. It seems that incremental updates would be more efficient in this scenario.

**Comment by Gowsky** [comment]
What kind of incremental updates, exactly, are you referring to?

The chart's content changes, so it has to be redrawn. This is normal, and it's how the Android canvas works. The results of heavy operations are cached, so they're not unnecessarily repeated.
